import React, { useState } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import loginCheckpoint from '@/api/auth/loginCheckpoint';
import { ActionCreator } from 'easy-peasy';
import { StaticContext } from 'react-router';
import { Form, useFormikContext, withFormik } from 'formik';
import useFlash from '@/plugins/useFlash';
import { FlashStore } from '@/state/flashes';
import FlashMessageRender from '@/components/FlashMessageRender';
import { GlowCard } from '@/components/ui/spotlight-card';

interface Values {
    code: string;
    recoveryCode: string;
}

type OwnProps = RouteComponentProps<Record<string, string | undefined>, StaticContext, { token?: string }>;

type Props = OwnProps & {
    clearAndAddHttpError: ActionCreator<FlashStore['clearAndAddHttpError']['payload']>;
};

const LoginCheckpointContainer = () => {
    const { isSubmitting, setFieldValue, values, errors, touched, handleChange, handleBlur } =
        useFormikContext<Values>();
    const [isMissingDevice, setIsMissingDevice] = useState(false);
    const activeField: keyof Values = isMissingDevice ? 'recoveryCode' : 'code';
    const activeDescription = isMissingDevice
        ? 'Enter one of the recovery codes generated when 2FA was enabled on your account.'
        : 'Enter the 6-digit authentication code generated by your authenticator app.';
    const activePlaceholder = isMissingDevice ? 'recovery code' : '000000';
    const activeError = touched[activeField] ? (errors[activeField] as string | undefined) : undefined;

    return (
        <div className='fixed inset-0 z-50 flex h-screen w-full overflow-hidden bg-[color:var(--card)] text-gray-100'>
            <style>{`
                .font-mono {
                    font-family: 'Space Mono', monospace;
                }
            `}</style>
            <div className='hidden h-full w-[70%] bg-[color:var(--card)] font-mono lg:block'>
                <span className='sr-only'>A dark neon background area.</span>
            </div>
            <div className='w-full overflow-y-auto bg-[color:var(--card)] px-8 font-mono sm:px-12 md:px-16 lg:w-[30%] lg:px-10 xl:px-12'>
                <div className='mx-auto flex h-full w-full max-w-md flex-col justify-center py-12'>
                    <div className='mb-10'>
                        <h1 className='text-4xl font-bold leading-tight tracking-tight text-[#f8f6ef] [text-shadow:0_0_14px_rgba(248,246,239,0.32)]'>
                            BurHan Console
                        </h1>
                    </div>

                    <div className='mb-6'>
                        <h2 className='text-sm font-bold uppercase tracking-wider text-gray-200'>DEVICE CHECKPOINT</h2>
                        <p className='mt-2 text-xs text-gray-400'>
                            {isMissingDevice
                                ? 'Use one backup recovery code to complete sign in.'
                                : 'Complete sign in with your two-factor authentication code.'}
                        </p>
                    </div>

                    <FlashMessageRender className='mb-4 px-1' />

                    <GlowCard
                        glowColor='green'
                        customSize
                        orbit
                        orbitDurationMs={2800}
                        className='w-full rounded-xl [--radius:12] [--border:2] [--size:185]'
                    >
                        <div className='rounded-xl bg-[color:var(--card)] p-8'>
                            <Form className='space-y-5'>
                                <div className='group space-y-1'>
                                    <label
                                        htmlFor={activeField}
                                        className='block text-xs uppercase text-gray-400 transition-colors group-focus-within:text-[color:var(--primary)]'
                                    >
                                        {isMissingDevice ? 'Recovery Code' : 'Authentication Code'}
                                    </label>
                                    <div className='relative'>
                                        <input
                                            name={activeField}
                                            type={'text'}
                                            value={values[activeField]}
                                            onChange={handleChange}
                                            onBlur={handleBlur}
                                            disabled={isSubmitting}
                                            id={activeField}
                                            autoComplete={'one-time-code'}
                                            autoFocus
                                            className='w-full rounded-lg border border-gray-800 bg-[color:var(--card)] px-4 py-3 pr-11 text-sm text-gray-100 outline-none transition-all placeholder:text-gray-500 focus:border-[color:var(--primary)] focus:ring-1 focus:ring-[color:var(--primary)]'
                                            placeholder={activePlaceholder}
                                        />
                                        <i className='fa-solid fa-shield-halved absolute right-4 top-1/2 -translate-y-1/2 text-xs text-gray-500' />
                                    </div>
                                    {activeError && (
                                        <div className='text-[10px] font-bold text-red-400'>{activeError}</div>
                                    )}
                                </div>

                                <p className='text-[10px] uppercase tracking-wide text-gray-500'>{activeDescription}</p>

                                <button
                                    type='submit'
                                    disabled={isSubmitting}
                                    className='mt-2 flex w-full items-center justify-center gap-2 rounded-lg bg-[color:var(--primary)] px-4 py-3 text-sm font-bold uppercase tracking-wide text-[color:var(--primary-foreground)] transition-all duration-300 hover:-translate-y-0.5 hover:shadow-[0_0_20px_rgba(var(--primary-rgb), 0.55)] disabled:opacity-50'
                                >
                                    {isSubmitting ? 'Verifying...' : 'Continue'}
                                    <i className='fa-solid fa-arrow-right text-xs' />
                                </button>
                            </Form>
                        </div>
                    </GlowCard>

                    <div className='mt-8 text-center'>
                        <button
                            type='button'
                            onClick={() => {
                                setFieldValue('code', '', false);
                                setFieldValue('recoveryCode', '', false);
                                setIsMissingDevice((s) => !s);
                            }}
                            disabled={isSubmitting}
                            className='text-xs uppercase tracking-wide text-gray-500 transition-colors hover:text-[color:var(--primary)] disabled:opacity-50'
                        >
                            {!isMissingDevice ? "I've Lost My Device" : 'I Have My Device'}
                        </button>
                    </div>

                    <div className='mt-6 text-center'>
                        <Link
                            className='text-xs text-gray-500 transition-colors hover:text-[color:var(--primary)]'
                            to={'/auth/login'}
                        >
                            Return to Login
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
};

const EnhancedForm = withFormik<Props, Values>({
    handleSubmit: ({ code, recoveryCode }, { setSubmitting, props: { clearAndAddHttpError, location } }) => {
        loginCheckpoint(location.state?.token || '', code, recoveryCode)
            .then((response) => {
                if (response.complete) {
                    // @ts-expect-error this is valid
                    window.location = response.intended || '/';
                    return;
                }

                setSubmitting(false);
            })
            .catch((error) => {
                console.error(error);
                setSubmitting(false);
                clearAndAddHttpError({ error });
            });
    },

    mapPropsToValues: () => ({
        code: '',
        recoveryCode: '',
    }),
})(LoginCheckpointContainer);

export default ({ history, location, ...props }: OwnProps) => {
    const { clearAndAddHttpError } = useFlash();

    if (!location.state?.token) {
        history.replace('/auth/login');

        return null;
    }

    return (
        <EnhancedForm clearAndAddHttpError={clearAndAddHttpError} history={history} location={location} {...props} />
    );
};
