import React, { useState } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import loginCheckpoint from '@/api/auth/loginCheckpoint';
import { ActionCreator } from 'easy-peasy';
import { StaticContext } from 'react-router';
import { Form, useFormikContext, withFormik } from 'formik';
import useFlash from '@/plugins/useFlash';
import { FlashStore } from '@/state/flashes';
import FlashMessageRender from '@/components/FlashMessageRender';

interface Values {
    code: string;
    recoveryCode: string;
}

type OwnProps = RouteComponentProps<Record<string, string | undefined>, StaticContext, { token?: string }>;

type Props = OwnProps & {
    clearAndAddHttpError: ActionCreator<FlashStore['clearAndAddHttpError']['payload']>;
};

const LoginCheckpointContainer = () => {
    const { isSubmitting, setFieldValue, values, errors, touched, handleChange, handleBlur } =
        useFormikContext<Values>();
    const [isMissingDevice, setIsMissingDevice] = useState(false);
    const activeField: keyof Values = isMissingDevice ? 'recoveryCode' : 'code';
    const activeDescription = isMissingDevice
        ? 'Enter one of the recovery codes generated when 2FA was enabled on your account.'
        : 'Enter the 6-digit authentication code generated by your authenticator app.';
    const activePlaceholder = isMissingDevice ? 'recovery code' : '000000';
    const activeError = touched[activeField] ? (errors[activeField] as string | undefined) : undefined;

    return (
        <div className='h-screen w-full overflow-hidden flex fixed inset-0 z-50' style={{ backgroundColor: '#ffffff' }}>
            <style>{`
                @import url('https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400&display=swap');
                .font-mono {
                    font-family: 'Space Mono', monospace;
                }
                .sharp-corners {
                    border-radius: 0;
                }
                .checkpoint-panel input:focus {
                    outline: none;
                    border-color: #000000 !important;
                    box-shadow: none;
                }
            `}</style>
            <div className='hidden lg:block w-[70%] h-full font-mono' style={{ backgroundColor: '#000000' }}>
                <span className='sr-only'>A minimalist solid black background area.</span>
            </div>
            <div
                className='checkpoint-panel w-full lg:w-[30%] h-full flex flex-col justify-center px-8 sm:px-12 md:px-16 lg:px-10 xl:px-12 overflow-y-auto font-mono'
                style={{ backgroundColor: '#ffffff' }}
            >
                <div className='w-full max-w-md mx-auto'>
                    <div className='mb-10'>
                        <h1 className='text-4xl font-bold leading-tight tracking-tight' style={{ color: '#000000' }}>
                            BurHan
                            <br />
                            CONSOLE
                        </h1>
                    </div>

                    <div className='mb-6'>
                        <h2 className='text-sm font-bold tracking-wider uppercase' style={{ color: '#000000' }}>
                            DEVICE CHECKPOINT
                        </h2>
                        <p className='mt-2 text-xs' style={{ color: '#6b7280' }}>
                            {isMissingDevice
                                ? 'Use one backup recovery code to complete sign in.'
                                : 'Complete sign in with your two-factor authentication code.'}
                        </p>
                    </div>

                    <FlashMessageRender className='mb-4 px-1' />

                    <Form className='space-y-5'>
                        <div className='relative'>
                            <input
                                name={activeField}
                                type={'text'}
                                value={values[activeField]}
                                onChange={handleChange}
                                onBlur={handleBlur}
                                disabled={isSubmitting}
                                id={activeField}
                                autoComplete={'one-time-code'}
                                autoFocus
                                className='w-full border bg-transparent px-4 py-3 text-sm focus:ring-0 sharp-corners'
                                style={{ borderColor: activeError ? '#ef4444' : '#000000', color: '#000000' }}
                                placeholder={activePlaceholder}
                            />
                            {activeError && (
                                <div className='absolute -bottom-5 left-0 text-[10px] text-red-500 font-bold'>
                                    {activeError}
                                </div>
                            )}
                        </div>

                        <p className='text-[10px] leading-relaxed uppercase tracking-wide' style={{ color: '#6b7280' }}>
                            {activeDescription}
                        </p>

                        <button
                            type='submit'
                            disabled={isSubmitting}
                            className='w-full py-4 text-xs font-bold tracking-wider sharp-corners border mt-2 transition-colors disabled:opacity-50 hover:opacity-90'
                            style={{ backgroundColor: '#000000', color: '#ffffff', borderColor: '#000000' }}
                        >
                            {isSubmitting ? 'VERIFYING...' : 'CONTINUE'}
                        </button>
                    </Form>

                    <div className='mt-8 text-center'>
                        <button
                            type='button'
                            onClick={() => {
                                setFieldValue('code', '', false);
                                setFieldValue('recoveryCode', '', false);
                                setIsMissingDevice((s) => !s);
                            }}
                            disabled={isSubmitting}
                            className='text-xs transition-colors hover:opacity-70 uppercase tracking-wide disabled:opacity-50'
                            style={{ color: '#6b7280' }}
                        >
                            {!isMissingDevice ? "I've Lost My Device" : 'I Have My Device'}
                        </button>
                    </div>

                    <div className='mt-6 text-center'>
                        <Link
                            className='text-xs transition-colors hover:opacity-70'
                            style={{ color: '#6b7280' }}
                            to={'/auth/login'}
                        >
                            Return to Login
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
};

const EnhancedForm = withFormik<Props, Values>({
    handleSubmit: ({ code, recoveryCode }, { setSubmitting, props: { clearAndAddHttpError, location } }) => {
        loginCheckpoint(location.state?.token || '', code, recoveryCode)
            .then((response) => {
                if (response.complete) {
                    // @ts-expect-error this is valid
                    window.location = response.intended || '/';
                    return;
                }

                setSubmitting(false);
            })
            .catch((error) => {
                console.error(error);
                setSubmitting(false);
                clearAndAddHttpError({ error });
            });
    },

    mapPropsToValues: () => ({
        code: '',
        recoveryCode: '',
    }),
})(LoginCheckpointContainer);

export default ({ history, location, ...props }: OwnProps) => {
    const { clearAndAddHttpError } = useFlash();

    if (!location.state?.token) {
        history.replace('/auth/login');

        return null;
    }

    return (
        <EnhancedForm clearAndAddHttpError={clearAndAddHttpError} history={history} location={location} {...props} />
    );
};
