import React, { useState } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import loginCheckpoint from '@/api/auth/loginCheckpoint';
import { ActionCreator } from 'easy-peasy';
import { StaticContext } from 'react-router';
import { Form, useFormikContext, withFormik } from 'formik';
import useFlash from '@/plugins/useFlash';
import { FlashStore } from '@/state/flashes';
import FlashMessageRender from '@/components/FlashMessageRender';
import { GlowCard } from '@/components/ui/spotlight-card';
import useSiteBranding from '@/hooks/useSiteBranding';
import {
    authErrorClass,
    authFieldLabelClass,
    authInputWithSuffixClass,
    authPrimaryButtonClass,
    burhanAuthThemeStyles,
} from '@/components/auth/authTheme';

interface Values {
    code: string;
    recoveryCode: string;
}

type OwnProps = RouteComponentProps<Record<string, string | undefined>, StaticContext, { token?: string }>;

type Props = OwnProps & {
    clearAndAddHttpError: ActionCreator<FlashStore['clearAndAddHttpError']['payload']>;
};

const getConfirmationToken = (location: OwnProps['location']): string => {
    return location.state?.token || new URLSearchParams(location.search).get('token') || '';
};

const LoginCheckpointContainer = () => {
    const { isSubmitting, setFieldValue, values, errors, touched, handleChange, handleBlur } =
        useFormikContext<Values>();
    const { name } = useSiteBranding();
    const [isMissingDevice, setIsMissingDevice] = useState(false);
    const activeField: keyof Values = isMissingDevice ? 'recoveryCode' : 'code';
    const activeDescription = isMissingDevice
        ? 'Enter one of the recovery codes generated when 2FA was enabled on your account.'
        : 'Enter the 6-digit authentication code generated by your authenticator app.';
    const activePlaceholder = isMissingDevice ? 'recovery-code' : '000000';
    const activeToken = isMissingDevice ? 'Recovery' : '2FA';
    const activeError = touched[activeField] ? (errors[activeField] as string | undefined) : undefined;

    return (
        <div className='burhan-auth-stage fixed inset-0 z-50 flex h-[100dvh] w-full overflow-hidden text-[color:var(--foreground)]'>
            <style>{burhanAuthThemeStyles}</style>
            <div className='burhan-auth-backdrop hidden h-full w-[70%] lg:block'>
                <span className='sr-only'>Dark neon background area.</span>
            </div>
            <div className='burhan-auth-rail h-full w-full overflow-y-auto px-6 py-5 sm:px-10 sm:py-6 md:px-14 lg:w-[30%] lg:overflow-y-hidden lg:px-8 lg:py-4 xl:px-10'>
                <div className='burhan-auth-shell mx-auto flex h-full min-h-0 w-full max-w-[32rem] flex-col justify-center py-0'>
                    <FlashMessageRender className='burhan-auth-flash mb-4 px-1' />

                    <GlowCard glowColor='green' customSize orbit orbitDurationMs={2800} className='burhan-auth-glow w-full max-h-full'>
                        <div className='burhan-auth-card'>
                            <div className='burhan-auth-brand-panel'>
                                <h1 className='burhan-auth-title'>{name}</h1>
                            </div>

                            <div className='mb-4 rounded-[1.35rem] border border-[rgba(255,255,255,0.06)] bg-[rgba(255,255,255,0.02)] px-4 py-3'>
                                <h2 className='text-[0.72rem] font-extrabold uppercase tracking-[0.18em] text-[rgba(248,246,239,0.72)]'>
                                    Device Checkpoint
                                </h2>
                                <p className='mt-2 text-sm leading-7 text-[rgba(151,160,171,0.94)]'>
                                    {isMissingDevice
                                        ? 'Use one backup recovery code to complete sign in.'
                                        : 'Complete sign in with your two-factor authentication code.'}
                                </p>
                            </div>

                            <Form className='burhan-auth-form'>
                                <div>
                                    <label htmlFor={activeField} className={authFieldLabelClass}>
                                        {isMissingDevice ? 'Recovery Code' : 'Authentication Code'}
                                    </label>
                                    <div className='burhan-auth-input-wrap'>
                                        <input
                                            name={activeField}
                                            type='text'
                                            value={values[activeField]}
                                            onChange={handleChange}
                                            onBlur={handleBlur}
                                            disabled={isSubmitting}
                                            id={activeField}
                                            autoComplete='one-time-code'
                                            autoFocus
                                            className={authInputWithSuffixClass}
                                            placeholder={activePlaceholder}
                                        />
                                        <span className='burhan-auth-field-token'>{activeToken}</span>
                                    </div>
                                    {activeError && <div className={authErrorClass}>{activeError}</div>}
                                </div>

                                <p className='burhan-auth-pin-copy text-sm'>{activeDescription}</p>

                                <button type='submit' disabled={isSubmitting} className={authPrimaryButtonClass}>
                                    {isSubmitting ? 'Verifying...' : 'Continue'}
                                    <i className='fa-solid fa-arrow-right-long text-sm' />
                                </button>
                            </Form>
                        </div>
                    </GlowCard>

                    <div className='mt-6 text-center'>
                        <button
                            type='button'
                            onClick={() => {
                                setFieldValue('code', '', false);
                                setFieldValue('recoveryCode', '', false);
                                setIsMissingDevice((state) => !state);
                            }}
                            disabled={isSubmitting}
                            className='burhan-auth-meta-link'
                        >
                            {!isMissingDevice ? "I've Lost My Device" : 'I Have My Device'}
                        </button>
                    </div>

                    <div className='mt-5 text-center'>
                        <Link className='burhan-auth-meta-link' to={'/auth/login'}>
                            Return to Login
                        </Link>
                    </div>
                </div>
            </div>
        </div>
    );
};

const EnhancedForm = withFormik<Props, Values>({
    handleSubmit: ({ code, recoveryCode }, { setSubmitting, props: { clearAndAddHttpError, location } }) => {
        loginCheckpoint(getConfirmationToken(location), code, recoveryCode)
            .then((response) => {
                if (response.complete) {
                    // @ts-expect-error this is valid
                    window.location = response.intended || '/';

                    return;
                }

                setSubmitting(false);
            })
            .catch((error) => {
                console.error(error);
                setSubmitting(false);
                clearAndAddHttpError({ error });
            });
    },

    mapPropsToValues: () => ({
        code: '',
        recoveryCode: '',
    }),
})(LoginCheckpointContainer);

export default ({ history, location, ...props }: OwnProps) => {
    const { clearAndAddHttpError } = useFlash();
    const token = getConfirmationToken(location);

    if (!token) {
        history.replace('/auth/login');

        return null;
    }

    return (
        <EnhancedForm clearAndAddHttpError={clearAndAddHttpError} history={history} location={location} {...props} />
    );
};
