<?php

namespace Pterodactyl\Services\Security\Rules;

class SecurityRuleCatalog
{
    public static function defaults(): array
    {
        return [
            [
                'key' => 'auth_brute_force',
                'name' => 'Authentication Brute Force',
                'description' => 'Repeated login failures, credential stuffing, or brute-force patterns on authentication routes.',
                'class' => 'auth_abuse',
                'surface' => 'auth',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 12,
                'window_seconds' => 900,
                'weight' => 3,
                'response_policy' => ['challenge', 'temp_block'],
                'cooldown_seconds' => 300,
                'agent_required' => false,
            ],
            [
                'key' => 'auth_checkpoint_abuse',
                'name' => 'Checkpoint and Recovery Abuse',
                'description' => 'Abuse of signup verification, captcha, password reset, and auth checkpoint flows.',
                'class' => 'auth_checkpoint_abuse',
                'surface' => 'auth',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 8,
                'window_seconds' => 900,
                'weight' => 4,
                'response_policy' => ['challenge', 'temp_block'],
                'cooldown_seconds' => 300,
                'agent_required' => false,
            ],
            [
                'key' => 'auth_honeypot_trigger',
                'name' => 'Auth Honeypot Trigger',
                'description' => 'Honeypot or trap form interaction that should not happen during legitimate use.',
                'class' => 'auth_probe',
                'surface' => 'auth',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 3600,
                'weight' => 10,
                'response_policy' => ['temp_block', 'block_ip'],
                'cooldown_seconds' => 1800,
                'agent_required' => false,
            ],
            [
                'key' => 'auth_honeyport_probe',
                'name' => 'Honeyport Probe',
                'description' => 'Network honeyport hit that strongly suggests opportunistic probing or automated attack traffic.',
                'class' => 'network_probe',
                'surface' => 'auth',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 3600,
                'weight' => 15,
                'response_policy' => ['temp_block', 'block_ip'],
                'cooldown_seconds' => 1800,
                'agent_required' => false,
            ],
            [
                'key' => 'api_ip_anomaly',
                'name' => 'API IP Anomaly',
                'description' => 'API token used from an IP outside its allowlist or from an unexpected origin.',
                'class' => 'api_abuse',
                'surface' => 'api',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 1800,
                'weight' => 10,
                'response_policy' => ['block_ip', 'revoke_api_token'],
                'cooldown_seconds' => 1800,
                'agent_required' => false,
            ],
            [
                'key' => 'bridge_signature_failure',
                'name' => 'Internal Bridge Signature Failure',
                'description' => 'Signed internal bridge request failed validation or arrived with a missing shared secret.',
                'class' => 'bridge_forgery',
                'surface' => 'bridge',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 900,
                'weight' => 10,
                'response_policy' => ['block_ip'],
                'cooldown_seconds' => 900,
                'agent_required' => false,
            ],
            [
                'key' => 'webhook_signature_failure',
                'name' => 'Webhook Signature Failure',
                'description' => 'A public webhook request failed signature validation or arrived while webhook secrets were missing.',
                'class' => 'webhook_forgery',
                'surface' => 'webhook',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 900,
                'weight' => 10,
                'response_policy' => ['block_ip'],
                'cooldown_seconds' => 900,
                'agent_required' => false,
            ],
            [
                'key' => 'upload_suspicious_attachment',
                'name' => 'Suspicious Attachment Upload',
                'description' => 'Attachment matched executable, script, or malware-style heuristics and should be quarantined.',
                'class' => 'upload_abuse',
                'surface' => 'upload',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 86400,
                'weight' => 10,
                'response_policy' => ['quarantine_artifact'],
                'cooldown_seconds' => 1800,
                'agent_required' => false,
            ],
            [
                'key' => 'agent_signature_failure',
                'name' => 'Security Agent Signature Failure',
                'description' => 'Security agent request failed HMAC validation, timestamp validation, or replay protection.',
                'class' => 'agent_forgery',
                'surface' => 'agent',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 900,
                'weight' => 10,
                'response_policy' => ['block_ip'],
                'cooldown_seconds' => 900,
                'agent_required' => false,
            ],
            [
                'key' => 'agent_silence',
                'name' => 'Agent Silence',
                'description' => 'Security agent stopped heartbeating or drifted beyond the configured heartbeat TTL.',
                'class' => 'agent_drift',
                'surface' => 'agent',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 10,
                'window_seconds' => 3600,
                'weight' => 10,
                'response_policy' => ['contain'],
                'cooldown_seconds' => 1800,
                'agent_required' => true,
            ],
            [
                'key' => 'origin_exhaustion',
                'name' => 'Origin Exhaustion / Volumetric DDoS',
                'description' => 'Origin appears saturated or connection flood exceeds the panel-origin mitigation boundary.',
                'class' => 'origin_ddos',
                'surface' => 'origin',
                'enabled' => true,
                'mode' => 'observe',
                'threshold' => 100,
                'window_seconds' => 300,
                'weight' => 100,
                'response_policy' => [],
                'cooldown_seconds' => 300,
                'agent_required' => true,
            ],
            [
                'key' => 'runtime_policy_block',
                'name' => 'Runtime Security Policy Block',
                'description' => 'Request was denied because the custom runtime denylist or route hold policy matched.',
                'class' => 'runtime_policy',
                'surface' => 'runtime',
                'enabled' => true,
                'mode' => 'active',
                'threshold' => 5,
                'window_seconds' => 900,
                'weight' => 5,
                'response_policy' => [],
                'cooldown_seconds' => 300,
                'agent_required' => false,
            ],
            [
                'key' => 'security_self_test_run',
                'name' => 'Security Self-Test Run',
                'description' => 'Manual validation run initiated by an administrator to verify core Security Center controls.',
                'class' => 'security_validation',
                'surface' => 'self_test',
                'enabled' => true,
                'mode' => 'observe',
                'threshold' => 1,
                'window_seconds' => 60,
                'weight' => 1,
                'response_policy' => [],
                'cooldown_seconds' => 60,
                'agent_required' => false,
            ],
        ];
    }
}
